ALTER TABLE login_credentials ADD COLUMN IF NOT EXISTS domain text;

INSERT INTO login_credentials (email, password_hash, domain) VALUES ('avyakta.tech@gmail.com', '$2b$10$UhAiHaMZYNJdkwUw6N6Tp.czk5GAjlsq4H5VSqcDPOgNZ/mOG1D6S', 'Technical') ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash, domain = EXCLUDED.domain;
INSERT INTO login_credentials (email, password_hash, domain) VALUES ('avyakta.design@gmail.com', '$2b$10$10430E/I6dLhCeC.9syDb.QLDqTyG1Yrabq5XAUJeFkpQDB/sgvdO', 'Design') ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash, domain = EXCLUDED.domain;
INSERT INTO login_credentials (email, password_hash, domain) VALUES ('avyakta.em@gmail.com', '$2b$10$HbxTmgFnjHa1GQwJPuiKuOs2AVzyZSSTSkx/5UP8Q5nvhPDsr.lsK', 'Event Management') ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash, domain = EXCLUDED.domain;
INSERT INTO login_credentials (email, password_hash, domain) VALUES ('avyakta.ed@gmail.com', '$2b$10$wZYp./hN/DKeF9j/ReOZVefxhKEVGUwyPN6gcgH9bSBTC4fPFUkP6', 'Ethics and Discipline') ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash, domain = EXCLUDED.domain;
INSERT INTO login_credentials (email, password_hash, domain) VALUES ('avyakta.media@gmail.com', '$2b$10$MyL.W6tZu3sU2KZyjQAxBeWFwMIo5OIUNpBzJDEXzBIemPQDRm3yK', 'Media and Visibility') ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash, domain = EXCLUDED.domain;
INSERT INTO login_credentials (email, password_hash, domain) VALUES ('avyakta.loops@gmail.com', '$2b$10$r6oH7R6aIo5zjrgrcW0WqOQMylcbJqxPP/TQOqYNkzaMiT81OSIDK', 'Logistics and Operations') ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash, domain = EXCLUDED.domain;
INSERT INTO login_credentials (email, password_hash, domain) VALUES ('avyakta.marketing@gmail.com', '$2b$10$l57mlRdqak/cqaZh4/QH2Oi6GPkqY5CVceHysMxZnoB2K55ITQ5D6', 'Marketing') ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash, domain = EXCLUDED.domain;
INSERT INTO login_credentials (email, password_hash, domain) VALUES ('avyakta.finance@gmail.com', '$2b$10$ilLppK6H81Os9iwDRMGzwOm7WEIbBLJmM7Zbh1/fIGeXVI50PEosy', 'Finance') ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash, domain = EXCLUDED.domain;
INSERT INTO login_credentials (email, password_hash, domain) VALUES ('avyakta.admin@gmail.com', '$2b$10$DtnHYb4jwMslUV61dutlcODU9cN9gKWC1RrLbtLNQ3EYSGNO1Zoku', NULL) ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash, domain = EXCLUDED.domain;
